#!/usr/bin/python

import argparse
from MyXray import MyXray

# Here's a reference PBI that shows the structure
# https://beyondtrust.atlassian.net/browse/EPM-16217
# Execution record: https://beyondtrust.atlassian.net/browse/EPM-21113

# Parse --pbi argument
parser = argparse.ArgumentParser()
parser.add_argument("--pbi", help="Create a test issue for the given PBI")
args = parser.parse_args()

# Create the issue
if args.pbi is None:
    throw("Please provide a PBI --pbi")

# Create an instance of MyXray pointing at this PBI
xray = MyXray(args.pbi)

# Create a test case linked to this PBI
test_case = xray.create_test_case('Test issue', 'This is a test issue')

print(f"Created {test_case.key}")

# Ask the user if they want to delete the issue
print(f"Delete {test_case.key}?")
delete = input("y/n: ")
if delete == "y":
    test_case.delete(deleteSubtasks=True)
